### ISSUE TITLE
You don't have permission to access /index.php on this server.

### ISSUE THREAD

**Issue by webshark25** [cerealcable/Steam-Authentication-for-XenForo#2]
Everything appears that its working, until I proceed back from steampowered.com to my forum... I get the following message

Forbidden
You don't have permission to access /index.php on this server.

from the url, http://example.com/index.php?register/steam&redirect=http%3A%2F%2Fexample.com%2Findex.php%3Faccount%2Fsteam&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198014798930&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198014798930&openid.return_to=http%3A%2F%2Fexample.com%2Findex.php%3Fregister%2Fsteam%26redirect%3Dhttp%253A%252F%252Fexample.com%252Findex.php%253Faccount%252Fsteam&openid.response_nonce=2012-03-08T03%3A15%3A45Z0%2BihUo1BA90OTWl0RT%2FTrDr4NQg%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=K6I6hWEneQ9X4vFBtfyhWjoaBuI%3D

---

Do you know what is wrong with this... I've followed all of the install instructions to a tee... My current CHMOD for index.php is 444... when I tried 0777 it wouldnt let me access my forum due to security issues, allowing everyone to use write.

**Comment by cerealcable** [comment]
Honestly, I have no idea what you have or haven't done that would have caused this issue.  I looked and found that an index.php on a working system has 0644 for its permissions.  You should try that.  Additionally you should quadruple check that it is redirecting you back to the correct index.php, which I cannot verify since you removed your domain from the link.

**Comment by webshark25** [comment]
It cuts off a bit of the link when you are looking at it through here, but when you click on it... you should be directed to the page that keeps having errors.

**Comment by cerealcable** [comment]
I'm not certain what could possibly cause this issue.  Is there anything in the error logs?  As far as how its possibly reverting to "404" I'm not certain but you might want to look into that.  You should attempt to install XenForo on a test system (that is not the same system where it is currently hosted) and seeing if the same issue occurs.

**Comment by webshark25** [comment]
I have multiple xenforo websites, one I host from a node right down the block from my house and I have access to the rack, so I might just bring my laptop and hook it into there and see if anything funky happens in the Apache server.

**Comment by cerealcable** [comment]
You also might want to open a support request with XenForo.  I don't believe this is a bug within this addon code but more likely some configuration issue.

**Comment by webshark25** [comment]
Yeah, I submitted the issue on xenforo's official website, and the website google sent me to when I tried to find a steam website. Thanks for the help thus far! Have a good one
